title: Polaris GP - Tarmo5 Build Competition
description: Official documentation and weekly instructions for the Polaris Grand Prix RC car build competition.
baseurl: ""
url: "https://saikhurana98.github.io/polaris-tarmo5-docs"

markdown: kramdown
