title: Polaris GP - Tarmo5 Build Competition
description: Official documentation and weekly instructions for the Polaris Grand Prix RC car build competition.
baseurl: "/polaris-tarmo5-docs"
url: "https://saikhurana98.github.io"

markdown: kramdown
theme: null
plugins: []

exclude:
  - mockup.html
  - event-mockup.html
  - "PolarisGP Announcement.pdf"
  - README.md
